global:
  scrape_interval: 15s # Frecuencia de recolecci√≥n
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      # IMPORTANTE: host.docker.internal permite a Docker ver tu localhost (donde corre Spring)
      - targets: ['host.docker.internal:8080']